import PropTypes from "prop-types";
import React from "react";

// Dummy data object for the receipt
const dummyReceiptData = {
  // Receipt details
  receiptDate: "02 July, 2030",
  paymentDate: "May 1, 2025",

  // From (Client) details
  from: {
    name: "Client registered name",
    gstin: "29AAZCA1833B1ZK",
    email: "contact@hiringdog.com",
    phone: "9916864727",
    address: {
      line1: "2SY No 7/2, K No 767/7, GPA M/S SLS,",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560068",
    },
  },

  // To (Company) details
  to: {
    name: "Adhyapan Education for Career Development Private Limited (HDIP)",
    gstin: "29AAZCA1833B1ZK",
    email: "contact@hiringdog.com",
    phone: "9916864727",
    address: {
      line1: "2SY No 7/2, K No 767/7, GPA M/S SLS,",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560068",
    },
  },

  // Payment details
  payment: {
    description: "Payment against Invoice (Apr 2025)",
    amount: 1234.56,
    amountInWords: "Rupees Ten Lakhs Only",
    mode: "Bank Transfer / UPI / NEFT",
  },

  // Bank details
  bankDetails: {
    accountName:
      "Adhyapan Education For Career Development Pvt Ltd",
    bank: "[ICICI / HDFC Bank]",
    accountNumber: "XXXXXXXXXXX",
    ifsc: "XXXX000XXXX",
    upi: "hiringdog@okhdcfbank",
  },

  // Company details for footer
  companyInfo: {
    fullName:
      "Adhyapan Education For Career Development Private Limited",
    gstin: "29AAZCA1833B1ZK",
    address:
      "#677, Spacelance, 1st Floor, 13th Cross, 27th Main Rd, 1st Sector, HSR Layout, Bengaluru, Karnataka 560102",
  },
};

const ReceiptPDF = ({ data = dummyReceiptData }) => {
  // Format currency function
  const formatCurrency = (amount) => {
    return `INR ${amount.toLocaleString("en-IN", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`;
  };

  // Define all the styles as objects
  const styles = {
    container: {
      width: "21cm",
      marginLeft: "auto",
      marginRight: "auto",
      backgroundColor: "white",
      paddingTop: "22px",
      fontFamily: "sans-serif",
    },
    header: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "flex-end",
      marginBottom: "15px",
    },
    logo: {
      width: "87px",
      height: "87px",
      backgroundColor: "#FEF3C7", // amber-100
      borderRadius: "0.375rem",
      overflow: "hidden",
    },
    logoImage: {
      width: "100%",
      height: "100%",
      objectFit: "cover",
    },
    title: {
      textAlign: "center",
      flexGrow: 1,
    },
    titleText: {
      fontSize: "33px",
      fontWeight: "bold",
    },
    dateSection: {
      textAlign: "right",
    },
    divider: {
      borderBottom: "1px solid black",
      margin: "15px 0",
    },
    fromToContainer: {
      display: "flex",
      marginBottom: "22px",
      border: "1px solid black",
      background:
        "linear-gradient(to right, #CCFFD9, #b0dbe9, #95baff)",
    },
    fromSection: {
      width: "50%",
      padding: "15px",
    },
    toSection: {
      width: "50%",
      padding: "15px",
    },
    sectionTitle: {
      fontSize: "18px",
      fontWeight: "bold",
      marginBottom: "7px",
      marginTop: 0,
    },
    boldText: {
      fontWeight: "bold",
    },
    detailsTable: {
      width: "100%",
      borderCollapse: "collapse",
      marginBottom: "17px",
      borderBottom: "1px solid black",
    },
    tableHeader: {
      padding: "11px",
      textAlign: "center",
      fontWeight: "bold",
      borderBottom: "1px solid black",
    },
    tableRow: {
      textAlign: "center",
    },
    tableRowAlternate: {
      textAlign: "center",
      background:
        "linear-gradient(to right, #CCFFD9, #b0dbe9, #95baff)",
    },
    tableCell: {
      padding: "11px",
      textAlign: "center",
      width: "50%",
    },
    amountInWords: {
      margin: "22px 0",
      fontWeight: "bold",
    },
    bankSection: {
      marginBottom: "22px",
    },
    bankTitle: {
      fontSize: "18px",
      fontWeight: "bold",
      marginBottom: "7px",
    },
    bankDetails: {
      marginLeft: "22px",
    },
    acknowledgementSection: {
      marginBottom: "22px",
    },
    acknowledgementTitle: {
      fontSize: "18px",
      fontWeight: "bold",
      marginBottom: "7px",
    },
    autoGenerated: {
      textAlign: "left",
      marginTop: "58px",
      marginBottom: "4px",
      color: "black",
      fontSize: "11px",
    },
    footer: {
      textAlign: "center",
      fontSize: "13px",
      borderTop: "1px solid black",
      paddingTop: "7px",
    },
  };

  return (
    <div style={styles.container}>
      {/* Header with logo and title */}
      <div style={styles.header}>
        <div style={styles.logo}>
          <img
            src="http://localhost:3000/static/images/hiring-dog-logo.png"
            alt="Hiring Dog Logo"
            style={styles.logoImage}
          />
        </div>
        <div style={styles.title}>
          <h1 style={styles.titleText}>RECEIPT</h1>
        </div>
        <div style={styles.dateSection}>
          <p>Date: {data.receiptDate}</p>
        </div>
      </div>

      {/* Divider line */}
      <div style={styles.divider}></div>

      {/* From and To sections */}
      <div style={styles.fromToContainer}>
        <div style={styles.fromSection}>
          <h2 style={styles.sectionTitle}>
            Received From:
          </h2>
          <p style={styles.boldText}>{data.from.name}</p>
          <p>GSTIN: {data.from.gstin}</p>
          <p>Mail Id: {data.from.email}</p>
          <p>Phone No: {data.from.phone}</p>
          <p>{data.from.address.line1}</p>
          <p>
            {data.from.address.city},{" "}
            {data.from.address.state} -{" "}
            {data.from.address.postalCode}
          </p>
        </div>
        <div style={styles.toSection}>
          <h2 style={styles.sectionTitle}>To:</h2>
          <p style={styles.boldText}>{data.to.name}</p>
          <p>GSTIN: {data.to.gstin}</p>
          <p>Mail Id: {data.to.email}</p>
          <p>Phone No: {data.to.phone}</p>
          <p>{data.to.address.line1}</p>
          <p>
            {data.to.address.city}, {data.to.address.state}{" "}
            - {data.to.address.postalCode}
          </p>
        </div>
      </div>

      {/* Description and Amount section */}
      <table style={styles.detailsTable}>
        <thead>
          <tr>
            <th
              style={{
                ...styles.tableHeader,
                width: "50%",
              }}
            >
              DESCRIPTION
            </th>
            <th
              style={{
                ...styles.tableHeader,
                width: "50%",
              }}
            >
              AMOUNT
            </th>
          </tr>
        </thead>
        <tbody>
          <tr style={styles.tableRow}>
            <td style={styles.tableCell}>
              {data.payment.description}
            </td>
            <td style={styles.tableCell}>
              {formatCurrency(data.payment.amount)}
            </td>
          </tr>
          <tr style={styles.tableRowAlternate}>
            <td style={styles.tableCell}>
              Mode of Payment
            </td>
            <td style={styles.tableCell}>
              {data.payment.mode}
            </td>
          </tr>
          <tr style={styles.tableRow}>
            <td style={styles.tableCell}>
              Date of Payment
            </td>
            <td style={styles.tableCell}>
              {data.paymentDate}
            </td>
          </tr>
        </tbody>
      </table>

      {/* Amount in words */}
      <div style={styles.amountInWords}>
        In Words: {data.payment.amountInWords}
      </div>

      {/* Bank details */}
      <div style={styles.bankSection}>
        <h3 style={styles.bankTitle}>Bank Credited To:</h3>
        <div style={styles.bankDetails}>
          <p>
            Account Name: {data.bankDetails.accountName}
          </p>
          <p>Bank: {data.bankDetails.bank}</p>
          <p>A/C No.: {data.bankDetails.accountNumber}</p>
          <p>IFSC: {data.bankDetails.ifsc}</p>
          <p>UPI (optional): {data.bankDetails.upi}</p>
        </div>
      </div>

      {/* Acknowledgement */}
      <div style={styles.acknowledgementSection}>
        <h3 style={styles.acknowledgementTitle}>
          Acknowledgement:
        </h3>
        <p>
          We acknowledge the receipt of the above payment
          towards professional interview services rendered
          by HDIP.
        </p>
      </div>

      {/* Auto-generated note */}
      <div style={styles.autoGenerated}>
        This is an auto-system generated receipt therefore
        signature is not required
      </div>

      {/* Footer */}
      <div style={styles.footer}>
        <p>
          {data.companyInfo.fullName}, GSTIN:{" "}
          {data.companyInfo.gstin}
        </p>
        <p>{data.companyInfo.address}</p>
      </div>
    </div>
  );
};

ReceiptPDF.displayName = "ReceiptPDF";

export default ReceiptPDF;

ReceiptPDF.propTypes = {
  data: PropTypes.object,
};
