name: Build and Push Docker Image

on:
  push:
    branches: [main]
  

jobs:
  node-server-deploy-build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # REQUIRED for Workload Identity Federation
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authentication to google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/981221757308/locations/global/workloadIdentityPools/github-pool/providers/github'
        service_account: 'github@hdip-platform.iam.gserviceaccount.com'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        #install_components: 'beta'

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev
     
    - name: Build & Push Docker image
      run: |
        docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/node-app:latest .
        docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/node-app:latest


    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy node-app \
          --image=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/node-app:latest \
          --platform=managed \
          --region=${{ secrets.REGION }} \
          --allow-unauthenticated
          --port=3000
      # --service-account=${{ secrets.GCP_SERVICE_KEY }}
